env:
  es6: true
  node: true
extends: 'standard'
rules:
  linebreak-style:
    - error
    - unix
  comma-dangle:
    - error
    - always-multiline
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  padded-blocks:
    - off
  no-warning-comments:
    - warn
  no-console:
    - warn
  no-var:
    - error
  no-multiple-empty-lines:
    - error
    - max: 2
  no-return-assign:
    - off
  no-path-concat:
    - off
