extends: 'standard'
env:
  node: true
parserOptions:
  ecmaVersion: 8
rules:
  linebreak-style:
    - error
    - unix
  comma-dangle:
    - error
    - always-multiline
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  padded-blocks:
    - off
  no-warning-comments:
    - warn
  no-console:
    - warn
  no-var:
    - error
  no-multiple-empty-lines:
    - error
    - max: 2
  no-return-assign:
    - off
  no-path-concat:
    - off
